import "./globals.css";
import { Anton } from "next/font/google";
import Navbar from "./navbar";
import UserProvider from "./UserContext";

const anton = Anton({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "NĀMAKA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-namaka-white ${anton.className}`}>
        <UserProvider>
          <Navbar />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
